[features]
seeds = false
skip-lint = false
anchor_version = "0.32.0"

[programs.localnet]
subscription = "HoTMwTrd7g4fGBX547LzGbH9FKju8QNVFAd9FGMLHRxq"

[programs.devnet]
subscription = "HoTMwTrd7g4fGBX547LzGbH9FKju8QNVFAd9FGMLHRxq"

[programs.mainnet]
subscription = "HoTMwTrd7g4fGBX547LzGbH9FKju8QNVFAd9FGMLHRxq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/*"]
