[toolchain]
anchor_version = "0.32.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
subscription = "45WGwEH24Y9J6ZHYoKiGRET4t4xpu6ESiTeRdhRf9pfr"

[programs.devnet]
subscription = "45WGwEH24Y9J6ZHYoKiGRET4t4xpu6ESiTeRdhRf9pfr"
recuro_guard = "4Fgs3dSAP869uEwsTd1tyh2pTkvLK1ji2BAhmfbBzCDr"

[programs.mainnet]
subscription = "45WGwEH24Y9J6ZHYoKiGRET4t4xpu6ESiTeRdhRf9pfr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/*"]
